// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl97MjAvPT1139b2pO2QvbSPBWZtA9W6w',
    appId: '1:433949561289:web:13addc6064b84058c79818',
    messagingSenderId: '433949561289',
    projectId: 'horizons-apps',
    authDomain: 'horizons-apps.firebaseapp.com',
    storageBucket: 'horizons-apps.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmqspCMkcMByzR2dv5msl5NmYx7KO9b4o',
    appId: '1:433949561289:android:7ac54451697ee805c79818',
    messagingSenderId: '433949561289',
    projectId: 'horizons-apps',
    storageBucket: 'horizons-apps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDonOd6rQSIt7a2V7mfSD8yp7QNUI_s2iE',
    appId: '1:433949561289:ios:819987d98d6d4f8ac79818',
    messagingSenderId: '433949561289',
    projectId: 'horizons-apps',
    storageBucket: 'horizons-apps.appspot.com',
    iosBundleId: 'com.example.horizons',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDonOd6rQSIt7a2V7mfSD8yp7QNUI_s2iE',
    appId: '1:433949561289:ios:819987d98d6d4f8ac79818',
    messagingSenderId: '433949561289',
    projectId: 'horizons-apps',
    storageBucket: 'horizons-apps.appspot.com',
    iosBundleId: 'com.example.horizons',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl97MjAvPT1139b2pO2QvbSPBWZtA9W6w',
    appId: '1:433949561289:web:3e0b0a69c7fa9084c79818',
    messagingSenderId: '433949561289',
    projectId: 'horizons-apps',
    authDomain: 'horizons-apps.firebaseapp.com',
    storageBucket: 'horizons-apps.appspot.com',
  );
}
